/* Generated By:JavaCC: Do not edit this line. MyParserTreeConstants.java Version 6.0_1 */
package parser;

public interface MyParserTreeConstants
{
  public int JJTDOPARSE = 0;


  public String[] jjtNodeName = {
    "doParse",
  };
}
/* JavaCC - OriginalChecksum=56dbcb7d1caf8076446ea78b3889d88f (do not edit this line) */
